name: trmnl-obsidian-daily-notes
services:
  soundingboard:
    image: ghcr.io/vaaski/trmnl-obsidian-daily-notes:latest
    ports:
      - 7834:7834
    environment:
      - TRMNL_API_KEY=

      - HASS_ADDRESS=
      - HASS_TOKEN=
      - HASS_ENTITIES=

      - BRIGHTSKY_LAT=
      - BRIGHTSKY_LON=

      - TRMNL_API_KEY=
    volumes:
      - /path/to/obsidian/daily/notes:/notes
