# https://taskfile.dev

version: "3"

tasks:
  trmnl:serve:
    cmds:
      - docker run --rm --name trmnlp --net host -v $(PWD)/trmnl-plugin:/plugin trmnl/trmnlp

  bun:dev:
    cmds:
      - bun run dev

  dev:
    deps: [bun:dev, trmnl:serve]
