# https://taskfile.dev

version: "3"

vars:
  DOCKER_TAG: ghcr.io/vaaski/trmnl-custom-plugins:latest

tasks:
  trmnl:serve:obsidian:
    cmds:
      - docker run --rm --name trmnlp --net host -v $(PWD)/trmnl-plugin/obsidian:/plugin trmnl/trmnlp

  bun:dev:
    cmds:
      - bun run dev

  dev:obsidian:
    deps: [bun:dev, trmnl:serve:obsidian]

  docker:build:
    cmds:
      - docker build -t {{.DOCKER_TAG}} .

  docker:run:
    dotenv: [".env"]
    cmds:
      - docker run --rm -it -p 7834:7834 -e SHARED_SECRET=$SHARED_SECRET -v $OBSIDIAN_DAILY_NOTES_PATH:/notes {{.DOCKER_TAG}}
