# https://taskfile.dev

version: "3"

dotenv: [".env"]

vars:
  DOCKER_TAG: ghcr.io/vaaski/trmnl-custom-plugins:latest
  DOCKER_SHARED_FLAGS: >-
    -e TRMNL_API_KEY=$TRMNL_API_KEY
  DOCKER_TRMNLP_FLAGS: >-
    {{.DOCKER_SHARED_FLAGS}}
    --rm --name trmnlp --net host
    -e TRMNL_ENDPOINT_NEWS=$TRMNL_ENDPOINT_NEWS
    -e TRMNL_ENDPOINT_OBSIDIAN=$TRMNL_ENDPOINT_OBSIDIAN
    -e TRMNL_ENDPOINT_HASS=$TRMNL_ENDPOINT_HASS
  DOCKER_BUN_FLAGS: >-
    {{.DOCKER_SHARED_FLAGS}}
    -v $OBSIDIAN_DAILY_NOTES_PATH:/notes
    -e SERVER_PORT=$SERVER_PORT
    -e HASS_ADDRESS=$HASS_ADDRESS
    -e HASS_TOKEN=$HASS_TOKEN
    -e HASS_ENTITIES=$HASS_ENTITIES
    -e BRIGHTSKY_LAT=$BRIGHTSKY_LAT
    -e BRIGHTSKY_LON=$BRIGHTSKY_LON

tasks:
  bun:dev:
    cmds:
      - bun run dev

  trmnl:serve:obsidian:
    cmds:
      - docker run -v $(PWD)/trmnl-plugin/obsidian:/plugin {{.DOCKER_TRMNLP_FLAGS}} trmnl/trmnlp

  trmnl:serve:hass-temp:
    cmds:
      - docker run -v $(PWD)/trmnl-plugin/hass-temp:/plugin {{.DOCKER_TRMNLP_FLAGS}} trmnl/trmnlp

  trmnl:serve:news:
    cmds:
      - docker run -v $(PWD)/trmnl-plugin/news:/plugin {{.DOCKER_TRMNLP_FLAGS}} trmnl/trmnlp

  dev:obsidian:
    deps: [bun:dev, trmnl:serve:obsidian]

  dev:hass-temp:
    deps: [bun:dev, trmnl:serve:hass-temp]

  dev:news:
    deps: [bun:dev, trmnl:serve:news]

# ------------------------------------------------------------------------------

  docker:build:
    cmds:
      - docker build -t {{.DOCKER_TAG}} .

  docker:run:
    deps: [docker:build]
    cmds:
      - docker run --rm -it -p 7834:7834 {{.DOCKER_BUN_FLAGS}} {{.DOCKER_TAG}}
