---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://trmnl.einkacken.com/notes
polling_headers: ''
id: 47284
name: obsidian-daily-notes
refresh_interval: 15
