name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build Image"
        run: |
          docker build . --tag ghcr.io/vaaski/trmnl-obsidian-daily-notes:latest
          docker push ghcr.io/vaaski/trmnl-obsidian-daily-notes:latest

      # - name: "Update instance"
      #   run: |
      #     curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}